apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:01b9rYkvBl8fyuNmBATZdekZb9wfe4PkGY2Swtg2DUqIIEoC/w==,iv:37J7ykqfiN1B1XVULK7/UNKj1U9uSd7i48geZMIqKXQ=,tag:9D5NWG2A/8kiBOlFNiZW/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uuh42wl8quepw69jzdq0rfdzyg90sny4ejw0ef7q7ukfjvza9urslykeej
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R29kOUMzK0dUVit4M1or
            eU1kbzBzcm1UQ2x4ZDJMcXVBdUdzckN3bmpjCmlFNmxZMXJTd09CVDNxbjkrUUZO
            emgxQkh2VDdqWkQ0MG9zZDhLQ0Q2LzQKLS0tIDFhbys5em5mNCtqTWg4ZlNTelZs
            bzRDdkFsTTVTNWV2OUVXMEpmVUlSNVEKA4ecN2zmg7m95IRV0CqLLnc6d0BQZ/2m
            pzxSnjRBqmfYElEr/poLaG+A56zbBzz24lgiKRthdHP2uDywWXij4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T23:08:05Z"
    mac: ENC[AES256_GCM,data:5aw8/CQ+6cUuxACg2rqo02VK40ngZwp7VgLPjAdsz9L3p6PKMT/F5nORSorPjgyl/3+0vfmWKeOL7inMFaAdCZH042RyPeMdcssK4Q18FAiR3bFy98derUNJcMqNTH4JA0h4vZVmTBcYjS2PJyXWWS2QXw3qRupra+9ottiTn3E=,iv:KaELW6DhWiA1KdlDlK+5O/tQHqHk+8YyJI8HpDbjaYw=,tag:oOiBww7QTXnob7KWa+zvwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
