---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Zurich"
  KUBE_VIP_ADDR: "192.168.1.101"
  METALLB_LB_RANGE: "192.168.1.110-192.168.1.120"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.110"
  METALLB_INGRESS_ADDR: "192.168.1.111"
